"""guardar que dia del plan cuenta cada sesion

Revision ID: 0a3efc993007
Revises: 32c9afea0a74
Create Date: 2026-09-30 16:17:28.606372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3efc993007'
down_revision: Union[str, None] = '32c9afea0a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Las sesiones que ya existen se quedan en NULL: no cuentan para ningún día.
    # Qué día cubría cada una lo decidía el botón pulsado, y eso no se guardó.
    op.add_column('entrenamientos', sa.Column('cubre_fecha', sa.Date(), nullable=True))
    op.create_unique_constraint('entrenamientos_usuario_id_cubre_fecha_key', 'entrenamientos', ['usuario_id', 'cubre_fecha'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('entrenamientos_usuario_id_cubre_fecha_key', 'entrenamientos', type_='unique')
    op.drop_column('entrenamientos', 'cubre_fecha')
    # ### end Alembic commands ###
