"""crear usuarios y grupos_musculares, actualizar ejercicios

Revision ID: 32c0db792aa1
Revises: 7ab408363597
Create Date: 2026-08-28 12:30:48.710016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32c0db792aa1'
down_revision: Union[str, None] = '7ab408363597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos_musculares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # Usuario único "sembrado": mientras no exista JWT, el backend trabaja con
    # esta fila fija (usuario_id hardcodeado en el código, ver app/auth.py).
    # Datos placeholder a propósito (repo público) — se sustituyen por
    # registro/login real al implementar autenticación.
    op.execute(
        "INSERT INTO usuarios (nombre, email, password_hash, created_at) "
        "VALUES ('Daniel', 'usuario@example.com', 'placeholder-sin-login-real', now())"
    )
    op.add_column('ejercicios', sa.Column('grupo_muscular_id', sa.Integer(), nullable=False))
    op.add_column('ejercicios', sa.Column('es_predefinido', sa.Boolean(), nullable=False))
    op.add_column('ejercicios', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('ejercicios', sa.Column('visibilidad', sa.String(length=20), nullable=False))
    op.add_column('ejercicios', sa.Column('activo', sa.Boolean(), nullable=False))
    op.add_column('ejercicios', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('ejercicios', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint('ejercicios_nombre_key', 'ejercicios', type_='unique')
    op.create_foreign_key(None, 'ejercicios', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'ejercicios', 'grupos_musculares', ['grupo_muscular_id'], ['id'])
    op.drop_column('ejercicios', 'creado_en')
    op.drop_column('ejercicios', 'grupo_muscular')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ejercicios', sa.Column('grupo_muscular', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('ejercicios', sa.Column('creado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ejercicios', type_='foreignkey')
    op.drop_constraint(None, 'ejercicios', type_='foreignkey')
    op.create_unique_constraint('ejercicios_nombre_key', 'ejercicios', ['nombre'])
    op.drop_column('ejercicios', 'updated_at')
    op.drop_column('ejercicios', 'created_at')
    op.drop_column('ejercicios', 'activo')
    op.drop_column('ejercicios', 'visibilidad')
    op.drop_column('ejercicios', 'usuario_id')
    op.drop_column('ejercicios', 'es_predefinido')
    op.drop_column('ejercicios', 'grupo_muscular_id')
    op.drop_table('usuarios')
    op.drop_table('grupos_musculares')
    # ### end Alembic commands ###
