"""crear notas_usuario_ejercicio

Revision ID: 546810f74f25
Revises: cb507868e1c0
Create Date: 2026-09-04 13:18:38.096658

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "546810f74f25"
down_revision: Union[str, None] = "cb507868e1c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notas_usuario_ejercicio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("ejercicio_id", sa.Integer(), nullable=False),
        sa.Column("nota", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ejercicio_id"], ["ejercicios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notas_usuario_ejercicio")
    # ### end Alembic commands ###
