"""crear programas, dias y periodos

Revision ID: c2563d398085
Revises: a86aaeb21ca7
Create Date: 2026-09-27 16:56:53.495715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2563d398085'
down_revision: Union[str, None] = 'a86aaeb21ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('oculto_desde', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programa_dias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('rutina_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('dia_semana BETWEEN 1 AND 7', name='programa_dias_dia_semana_check'),
    sa.ForeignKeyConstraint(['programa_id'], ['programas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programa_id', 'dia_semana', name='programa_dias_programa_id_dia_semana_key')
    )
    op.create_table('programa_periodos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('desde', sa.Date(), nullable=False),
    sa.Column('hasta', sa.Date(), nullable=True),
    sa.CheckConstraint('hasta IS NULL OR hasta >= desde', name='programa_periodos_rango_check'),
    sa.ForeignKeyConstraint(['programa_id'], ['programas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_programa_periodos_usuario_abierto', 'programa_periodos', ['usuario_id'], unique=True, postgresql_where=sa.text('hasta IS NULL'))
    # Lo sustituye programa_dias. Se borra sin pasar su texto ("Lunes") a días de
    # un programa: era solo orientativo y no había datos que conservar.
    op.drop_column('rutinas', 'dia_habitual')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rutinas', sa.Column('dia_habitual', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index('ix_programa_periodos_usuario_abierto', table_name='programa_periodos', postgresql_where=sa.text('hasta IS NULL'))
    op.drop_table('programa_periodos')
    op.drop_table('programa_dias')
    op.drop_table('programas')
    # ### end Alembic commands ###
