"""crear entrenamientos y series

Revision ID: cb507868e1c0
Revises: ba5ce4fd56a1
Create Date: 2026-09-01 22:21:26.819739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb507868e1c0'
down_revision: Union[str, None] = 'ba5ce4fd56a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrenamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rutina_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('notas', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrenamiento_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('repeticiones', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('variante', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entrenamiento_id'], ['entrenamientos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['rutina_slots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series')
    op.drop_table('entrenamientos')
    # ### end Alembic commands ###
