"""anadir terminada_en a entrenamientos

Revision ID: e02ac0d16118
Revises: 546810f74f25
Create Date: 2026-09-27 16:06:16.713760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e02ac0d16118'
down_revision: Union[str, None] = '546810f74f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrenamientos', sa.Column('terminada_en', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Las sesiones que ya existían se dan por terminadas: si no, la de hoy
    # aparecería como abierta sin que nadie la hubiera dejado a medias.
    op.execute("UPDATE entrenamientos SET terminada_en = updated_at")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entrenamientos', 'terminada_en')
    # ### end Alembic commands ###
